### ISSUE TITLE
Cannot override index for all types of metadata

### ISSUE THREAD

**Issue by brandon-fryslie** [splunk/splunkforjenkins#1]
I'm Jenkins version 2.57 and Splunk Plugin version 1.5.1.  I would like to configure all types of metadata to use the 'main' index in Splunk.  I have added all types of metadata to the plugin settings with the 'Index' set to 'main'.  However, the plugin still uses the index 'jenkins_console' when sending the console logs for the Jenkins master.  This causes a large stream of errors in the console which prevent me from using the plugin.  Internally, this is the 'LOG' event type which cannot be disabled with configuration.

To reproduce:
- Set up Splunk with a main index
- Install plugin on fresh Jenkins master
- Configure plugin with host and api token for Splunk
- Configure plugin to set all types of metadata to send to Index 'main'
- Enable plugin and run a job
- Many errors are printed because Jenkins is sending the LOG event type to the 'jenkins_console' index

Expected behavior:
- LOG event type is configurable in the UI to allow it to be disabled and set the index

**Comment by fengxx** [comment]
Thanks for reporting the issue, it is fixed by ed349d4cdffbf6fa2aab368c524a0f128fe5ff33, LOG will follow the index setting from "Console Log".
By the way, the repo is under[ jenkins org](https://github.com/jenkinsci/splunk-devops-plugin) now

**Comment by jeffersongirao** [comment]
@fengxx Hello! Do you have any idea when this fix is going to be released? Thanks!

**Comment by fengxx** [comment]
released 1.5.2, may take a  day to appear on jenkins update center.
