### ISSUE TITLE
Invalid cookie header messages when using AWS ALB/ELB

### ISSUE THREAD

**Issue by mikenau** [splunk/splunkforjenkins#10]
We see a flood of these messages when using this plugin within Jenkins that is accessible behind and AWS ALB or ELB. 
```
Invalid cookie header: "Set-Cookie: AWSALB=Bcc6monuRmkSMxvJizAAzShSAZwyD0YxecrNZNs549m7C7oQODpGFpT8rI2/vRAGumOB+tygNnKqzXn0Pw08vohShibr2CCpKMLCdRxXwY/NAXpZyUPZxh3yjzxt; Expires=Fri, 11 Jan 2019 19:37:52 GMT; Path=/". Invalid 'expires' attribute: Fri, 11 Jan 2019 19:37:52 GMT
```
The root cause appears to be the HTTP Client version used. This was fixed as part of https://issues.apache.org/jira/browse/HTTPCLIENT-1077. I suspect the Jenkins Splunk plugin is using a pretty old version of HTTP Client.

**Comment by fengxx** [comment]
fix was merged
