### ISSUE TITLE
Unable to NOT send job console log

### ISSUE THREAD

**Issue by hallm4** [splunk/splunkforjenkins#11]
I'm trying to disable sending the job console logs into Splunk. Several of our jobs are "problematic" in that they log too much. 

With our Pipeline jobs, they do not send console log from jobs because we do not have the appropriate plugin/Pipeline code. 

With Freestyle jobs, I'm unable to find a way to toggle them off in the GUI config. Is there another way?

**Comment by fengxx** [comment]
added `splunkins.consoleLogFilterPattern` system property in 1.7.1 https://github.com/jenkinsci/splunk-devops-plugin
