### ISSUE TITLE
Multiple Splunk indexer hostnames not working

### ISSUE THREAD

**Issue by starless72** [splunk/splunkforjenkins#15]
Hi,
in the Splunk for Jenkins Configuration, the "HTTP Input Host" field is supposed to support multiple hostnames/IPs, separated by comma. But actually it does not work, only the first element in the list is used.
This has been verified on plugin version 1.9.1 on Jenkins 2.204.2.
Do you have any clues?
Thanks.

**Comment by fengxx** [comment]
this repo moved to https://github.com/jenkinsci/splunk-devops-plugin as a Jenkins plugin hosting requirement

multiple hostnames are used for fail-over, not load balancing. When your first host is down or inaccessible, the 2nd will be used
