### ISSUE TITLE
Need info on setting to disable all event type except console log

### ISSUE THREAD

**Issue by jeevatkm** [splunk/splunkforjenkins#17]
@fengxx First of all, I'm sorry for creating an help question here. I did not see an option to ask on https://github.com/jenkinsci/splunk-devops-plugin

For our use case, I want to disable all the events from Splunk Jenkins plugin and **keep only Console log push** to Splunk via `sendSplunkConsoleLog` or another option.

Can you please provide some insights here?

**Comment by fengxx** [comment]
see also https://plugins.jenkins.io/splunk-devops/  Configure Metadata
<img width="937" alt="Screen Shot 2020-06-12 at 3 05 17 PM" src="https://user-images.githubusercontent.com/661416/84475827-c90c9f00-acbf-11ea-99e4-8e65d888a7bd.png">
