### ISSUE TITLE
What license does the project use

### ISSUE THREAD

**Issue by angry-cellophane** [splunk/splunkforjenkins#3]
Hi, 

I can't find information about what license is used. Please can you specify the license in readme and add the license file to the project like it's done in aws plugin - https://github.com/jenkinsci/pipeline-aws-plugin

**Comment by angry-cellophane** [comment]
Should it use Apache 2?

**Comment by angry-cellophane** [comment]
@fengxx  what do you think about it?

**Comment by fengxx** [comment]
As most of Jenkins plugins, it is MIT
https://github.com/splunk/splunkforjenkins/blob/master/pom.xml#L22

The license will show up on JENKINS_URL/about
