### ISSUE TITLE
Unit test total in Splunk does not match what's in Jenkins

### ISSUE THREAD

**Issue by ray2kool** [splunk/splunkforjenkins#6]
The test totals in Splunk does not match what is in Jenkins for some builds. 

See attached screenshots. Splunk show test totals are 928. Jenkins show test totals as 426.

The problem does not occur for all Jenkins jobs. We think it may be due to using TestNG, but we have not confirmed this is the root cause.

![splunk](https://user-images.githubusercontent.com/11618464/39787944-bf9fd3fe-52dc-11e8-962e-a63ab4f7b9ac.png)
![jenkins](https://user-images.githubusercontent.com/11618464/39787945-bfbd0492-52dc-11e8-8a08-ccc68ae345aa.png)

**Comment by fengxx** [comment]
From the screenshot, there are two Test results link, I guess the job used both Junit test result publisher and TestNG publisher,  the test_summary sums up all the numbers, could you please check the detailed test result in `index=jenkins build_url=x`

**Comment by ray2kool** [comment]
@fengxx Sorry, didn't see your comment till now. There are a couple reasons for this issue.

- First reason is what you mentioned. The job was publishing both Junit and TestNG results, and the plugin is totaling results from both.

- Second reason is in TestNG results, the test-method can have an `is-config=true` property. Jenkins is only counting test methods where is-config property is not set (or set to false) in the test totals. The plugin is counting all test methods in the total.

**Comment by fengxx** [comment]
Thanks for the bug report, I fixed the 2nd item via commit https://github.com/splunk/splunkforjenkins/commit/345be68d12e233ac53a64e376c88113c7b35
